import { pool } from '../config/database';

const products = [
  {
    category: 'New drop',
    highlight: 'Best seller',
    name: 'Brazil Collection Tee',
    description: 'Lightweight cotton tee with a clean everyday fit.',
    price: '$32.90',
    priceValue: 32.9,
    brand: 'Urban Stitch',
    type: 'T-Shirts',
  },
  {
    category: 'Basics',
    highlight: 'Soft touch',
    name: 'Essential Hoodie',
    description: 'Relaxed hoodie made for layering and comfort.',
    price: '$58.90',
    priceValue: 58.9,
    brand: 'Minimal Wear',
    type: 'Blouses',
  },
  {
    category: 'Accessories',
    highlight: 'Limited',
    name: 'Canvas Tote',
    description: 'Structured tote for daily carry and quick errands.',
    price: '$18.90',
    priceValue: 18.9,
    brand: 'EcoWeave',
    type: 'Bags',
  },
  {
    category: 'New drop',
    highlight: 'Trending',
    name: 'Linen Resort Shirt',
    description: 'Breathable linen shirt, ideal for warm-weather looks.',
    price: '$89.90',
    priceValue: 89.9,
    brand: 'TropiCool',
    type: 'Shirts',
  },
  {
    category: 'Basics',
    highlight: 'Everyday',
    name: 'Slim Chino Pants',
    description: 'Tailored chinos in stretch cotton twill.',
    price: '$129.90',
    priceValue: 129.9,
    brand: 'Urban Stitch',
    type: 'Pants',
  },
  {
    category: 'Accessories',
    highlight: 'New',
    name: 'Leather Belt',
    description: 'Full-grain leather belt with brushed metal buckle.',
    price: '$49.90',
    priceValue: 49.9,
    brand: 'Nomad Essentials',
    type: 'Belts',
  },
  {
    category: 'Shoes',
    highlight: 'Comfort',
    name: 'Cloud Runner Sneakers',
    description: 'Lightweight sneakers with memory foam insole.',
    price: '$199.90',
    priceValue: 199.9,
    brand: 'Urban Stitch',
    type: 'Sneakers',
  },
  {
    category: 'New drop',
    highlight: 'Exclusive',
    name: 'Silk Blend Dress',
    description: 'Midi dress with a flattering wrap silhouette.',
    price: '$249.90',
    priceValue: 249.9,
    brand: 'Minimal Wear',
    type: 'Dresses',
  },
  {
    category: 'Basics',
    highlight: 'Value',
    name: 'Cotton Crew Neck 3-Pack',
    description: 'Three essential crew neck tees in neutral tones.',
    price: '$69.90',
    priceValue: 69.9,
    brand: 'Minimal Wear',
    type: 'T-Shirts',
  },
  {
    category: 'Accessories',
    highlight: 'Summer',
    name: 'Round Sunglasses',
    description: 'UV400 protection with gold-tone metal frames.',
    price: '$79.90',
    priceValue: 79.9,
    brand: 'TropiCool',
    type: 'Sunglasses',
  },
  {
    category: 'Shoes',
    highlight: 'Best seller',
    name: 'Leather Loafers',
    description: 'Hand-stitched penny loafers in burnished leather.',
    price: '$279.90',
    priceValue: 279.9,
    brand: 'Nomad Essentials',
    type: 'Shoes',
  },
  {
    category: 'Basics',
    highlight: 'Soft',
    name: 'Ribbed Tank Top',
    description: 'Fitted rib-knit tank, layers perfectly under jackets.',
    price: '$39.90',
    priceValue: 39.9,
    brand: 'EcoWeave',
    type: 'Blouses',
  },
  {
    category: 'New drop',
    highlight: 'Statement',
    name: 'Oversized Denim Jacket',
    description: 'Vintage-wash denim jacket with a relaxed boxy fit.',
    price: '$179.90',
    priceValue: 179.9,
    brand: 'Urban Stitch',
    type: 'Jackets',
  },
  {
    category: 'Accessories',
    highlight: 'Trending',
    name: 'Braided Bracelet Set',
    description: 'Set of three hand-braided cotton bracelets.',
    price: '$24.90',
    priceValue: 24.9,
    brand: 'TropiCool',
    type: 'Jewelry',
  },
  {
    category: 'Basics',
    highlight: 'Stretch',
    name: 'Relaxed Fit Shorts',
    description: 'Drawstring shorts in breathable cotton-linen blend.',
    price: '$64.90',
    priceValue: 64.9,
    brand: 'EcoWeave',
    type: 'Shorts',
  },
  {
    category: 'Shoes',
    highlight: 'Minimal',
    name: 'Flat Leather Sandals',
    description: 'Handmade leather sandals with a cushioned footbed.',
    price: '$119.90',
    priceValue: 119.9,
    brand: 'Nomad Essentials',
    type: 'Sandals',
  },
  {
    category: 'New drop',
    highlight: 'Premium',
    name: 'Wool Blend Blazer',
    description: 'Unstructured blazer in lightweight wool blend.',
    price: '$349.90',
    priceValue: 349.9,
    brand: 'Minimal Wear',
    type: 'Jackets',
  },
  {
    category: 'Accessories',
    highlight: 'Classic',
    name: 'Embroidered Baseball Cap',
    description: 'Six-panel cap with embroidered logo and adjustable strap.',
    price: '$44.90',
    priceValue: 44.9,
    brand: 'Urban Stitch',
    type: 'Caps',
  },
  {
    category: 'Basics',
    highlight: 'Lightweight',
    name: 'Linen Wide-Leg Pants',
    description: 'Flowy wide-leg pants in premium washed linen.',
    price: '$139.90',
    priceValue: 139.9,
    brand: 'TropiCool',
    type: 'Pants',
  },
  {
    category: 'Accessories',
    highlight: 'Modern',
    name: 'Minimalist Watch',
    description: 'Japanese quartz movement with a stainless steel case.',
    price: '$229.90',
    priceValue: 229.9,
    brand: 'Nomad Essentials',
    type: 'Watches',
  },
  {
    category: 'New drop',
    highlight: 'Elegant',
    name: 'Pleated Midi Skirt',
    description: 'Flowy pleated skirt with an elasticated waistband.',
    price: '$109.90',
    priceValue: 109.9,
    brand: 'Minimal Wear',
    type: 'Skirts',
  },
  {
    category: 'Shoes',
    highlight: 'Athletic',
    name: 'Trail Runner Hiking Shoes',
    description: 'Grippy outsole and waterproof membrane for trail runs.',
    price: '$319.90',
    priceValue: 319.9,
    brand: 'Urban Stitch',
    type: 'Sneakers',
  },
  {
    category: 'Basics',
    highlight: 'Organic',
    name: 'Hemp Blend Pullover',
    description: 'Relaxed-fit pullover in soft hemp-cotton blend.',
    price: '$94.90',
    priceValue: 94.9,
    brand: 'EcoWeave',
    type: 'Blouses',
  },
  {
    category: 'Accessories',
    highlight: 'Bold',
    name: 'Resin Statement Earrings',
    description: 'Lightweight geometric earrings in marbled resin.',
    price: '$34.90',
    priceValue: 34.9,
    brand: 'TropiCool',
    type: 'Jewelry',
  },
];

export async function seedProducts(): Promise<void> {
  const { rows } = await pool.query('SELECT COUNT(*)::int AS count FROM products');

  if (rows[0].count > 0) {
    console.log(`Products table already seeded (${rows[0].count} rows). Skipping.`);
    return;
  }

  const query = `
    INSERT INTO products (category, highlight, name, description, price, price_value, brand, type)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
  `;

  for (const product of products) {
    await pool.query(query, [
      product.category,
      product.highlight,
      product.name,
      product.description,
      product.price,
      product.priceValue,
      product.brand,
      product.type,
    ]);
  }

  console.log(`Seeded ${products.length} products.`);
}
